USE ROLE ACCOUNTADMIN;


CREATE OR REPLACE WAREHOUSE WH_DEV 
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60 
    AUTO_RESUME = TRUE 
    INITIALLY_SUSPENDED = TRUE; 


CREATE OR REPLACE DATABASE POC_DEV; 

CREATE OR REPLACE SCHEMA POC_DEV.BRONZE; 
CREATE OR REPLACE SCHEMA POC_DEV.SILVER; 
CREATE OR REPLACE SCHEMA POC_DEV.GOLD; 

CREATE OR REPLACE ROLE ROLE_POC_READONLY;
CREATE OR REPLACE ROLE ROLE_DBT_DEV;