
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT
  ON SCHEMA POC_DEV.BRONZE TO ROLE ROLE_DBT_DEV;

GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT
  ON SCHEMA POC_DEV.SILVER TO ROLE ROLE_DBT_DEV;

GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT
  ON SCHEMA POC_DEV.GOLD TO ROLE ROLE_DBT_DEV;

GRANT USAGE 
    ON SCHEMA POC_DEV.GOLD TO ROLE ROLE_POC_READONLY; 

GRANT SELECT 
    ON ALL TABLES IN SCHEMA POC_DEV.GOLD 
    TO ROLE ROLE_POC_READONLY; 


GRANT SELECT 
    ON FUTURE TABLES IN SCHEMA POC_DEV.GOLD 
    TO ROLE ROLE_POC_READONLY; 

GRANT SELECT 
    ON ALL VIEWS IN SCHEMA POC_DEV.GOLD 
    TO ROLE ROLE_POC_READONLY; 


GRANT SELECT 
    ON FUTURE VIEWS IN SCHEMA POC_DEV.GOLD 
    TO ROLE ROLE_POC_READONLY; 


grant usage, operate on warehouse wh_dev to role ROLE_DBT_DEV;

grant usage on database poc_dev to role role_dbt_dev; 

grant usage on schema poc_dev.bronze to role role_dbt_dev; 
grant usage on schema poc_dev.silver to role role_dbt_dev; 
grant usage on schema poc_dev.gold to role role_dbt_dev; 

grant usage on database poc_dev to role role_poc_readonly; 

GRANT ROLE ROLE_POC_READONLY TO ROLE ROLE_DBT_DEV;

-- dbt role needs to see and use things
GRANT USAGE, OPERATE ON WAREHOUSE WH_DEV TO ROLE ROLE_DBT_DEV;
GRANT USAGE ON DATABASE POC_DEV TO ROLE ROLE_DBT_DEV;
GRANT USAGE ON SCHEMA POC_DEV.BRONZE TO ROLE ROLE_DBT_DEV;
GRANT USAGE ON SCHEMA POC_DEV.SILVER TO ROLE ROLE_DBT_DEV;
GRANT USAGE ON SCHEMA POC_DEV.GOLD   TO ROLE ROLE_DBT_DEV;

-- readonly should have db + schema usage
GRANT USAGE ON DATABASE POC_DEV TO ROLE ROLE_POC_READONLY;
GRANT USAGE ON SCHEMA POC_DEV.GOLD TO ROLE ROLE_POC_READONLY;


